# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf5f9c751b18adaf32d77bed913c6cd9c2a86f177a81e97c49d169093894d5c39086cf251ca58e4804e8fbddfb522fa36978ad0005f8a10a6877f396b5d0102b

test:
  secret_key_base: 4dc621ddd81d657e2ffd651cd6ca7bfb3d9c3ebff3d9a827e3af7846069564da0e5375e36ce03e6b3a5a341a6e424d330e03cfcf513ebf049294f71acea88d9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
